# Generated by Django 4.1.2 on 2022-12-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="tweet",
        ),
        migrations.AddField(
            model_name="media",
            name="type",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tweets",
            name="media_urls",
            field=models.ManyToManyField(to="tweets.media"),
        ),
        migrations.AlterField(
            model_name="media",
            name="id",
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="media",
            name="url",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tweets",
            name="url",
            field=models.CharField(max_length=255),
        ),
    ]
