# Generated by Django 4.1.2 on 2022-12-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_remove_media_tweet_media_type_tweets_media_urls_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweets",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweets",
            name="username",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
