# Generated by Django 4.1.2 on 2022-12-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0003_tweets_name_tweets_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweets",
            name="profile_image",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweets",
            name="protected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tweets",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tweets",
            name="is_media",
            field=models.BooleanField(default=False, max_length=64),
        ),
    ]
