# Generated by Django 4.1.2 on 2023-01-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0004_tweets_profile_image_tweets_protected_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweets",
            old_name="profile_image",
            new_name="image",
        ),
    ]
