# Generated by Django 4.1.2 on 2023-03-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0007_alter_tweets_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweets",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
