# Generated by Django 4.1.2 on 2023-03-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0008_alter_tweets_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweets",
            options={"ordering": ["created"]},
        ),
    ]
