# Generated by Django 4.1.2 on 2022-10-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_at', models.CharField(max_length=255)),
            ],
        ),
    ]
