# Generated by Django 4.1.2 on 2022-10-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_at",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_name",
            new_name="username",
        ),
    ]
