# Generated by Django 4.1.2 on 2022-12-04 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_followers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Followers",
            new_name="TwitterFollowers",
        ),
        migrations.CreateModel(
            name="TwitterFollowing",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("profile_image_url", models.CharField(max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.twitteruser",
                    ),
                ),
            ],
        ),
    ]
