# Generated by Django 4.1.2 on 2022-12-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
        ("users", "0005_rename_followers_twitterfollowers_twitterfollowing"),
    ]

    operations = [
        migrations.AddField(
            model_name="twitteruser",
            name="bookmarks",
            field=models.ManyToManyField(to="tweets.tweets"),
        ),
    ]
