# Generated by Django 4.1.2 on 2022-12-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_twitteruser_bookmarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwitterAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
            ],
        ),
    ]
