# Generated by Django 4.1.2 on 2022-12-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_twitteraccesstoken_refresh_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="twitteruser",
            name="first_bookmark",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
