# Generated by Django 4.1.2 on 2023-03-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_twitteruser_twitter_oauth_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitteruser",
            name="twitter_access_token",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="users.twitteraccesstoken",
            ),
        ),
    ]
